### PR TITLE
More enhancements to the minimatch algorithm. All tests are now green.

### PR DESCRIPTION
**Pull request by piotrtomiak**
This PR makes Minimatch java as compatible with JS Minimatch as possible. Some corner cases are just not supported by Java RegExp. Patterns test has been added to the suite.

Braces expansion is still TBD.

To boost up performance and remove amount of entry points to minimatch algorithm, I have simplified PathAdapter API to one method, which returns an array for a given path. This will require a change in tern.java.

### CODE REVIEW

**Comment by piotrtomiak** [comment]
By the way, what debugger are you using to debug NodeJS code? Have you tried Webclipse JS Debugger?

**Comment by angelozerr** [comment]
> Braces expansion is still TBD.

Yes I will do that as soon as possible.

> To boost up performance and remove amount of entry points to minimatch algorithm, I have simplified PathAdapter API to one method, which returns an array for a given path. This will require a change in tern.java.

Great! Could you do a PR please for tern.java?

> By the way, what debugger are you using to debug NodeJS code? 

None, because I'm developping my tern plugin with Chrome. For minimatch case I use https://github.com/angelozerr/minimatch.java/tree/master/html

> Have you tried Webclipse JS Debugger?

I have donwloaded it, now I must test it!

**Comment by angelozerr** [comment]
Thanks again @piotrtomiak!

**Comment by piotrtomiak** [comment]
> Great! Could you do a PR please for tern.java?

Sure. Will try to do it today.

> > By the way, what debugger are you using to debug NodeJS code?
> 
> None, because I'm developping my tern plugin with Chrome. For minimatch case I use https://github.com/angelozerr/minimatch.java/tree/master/html
> 
> > Have you tried Webclipse JS Debugger?
> 
> I have donwloaded it, now I must test it!

Definitely! Along with your tern support, I found debugging experience almost as good as with Java. Really interested in your comments!

**Comment by angelozerr** [comment]
@piotrtomiak I think it should be very cool if Webclipse JS Debugger could give a support for debugging tern. I mean launch ternjs with node in debug mode. After that user set a breakpoint to the tern or her tern plugin. It opens completion with Eclipse and debugger plays his goal. I have written something about debugging with nodeclipse at https://github.com/angelozerr/tern.java/wiki/Debugging-tern.js-with-Nodeclipse but if Webclipse could provide a launch (ex : select your project and do Debug Tern)).

If you need help or info about that don't hesitate to tell me. A lot of tern developers tell how to debug ternjs. Webclipse could be a great solution:)

**Comment by angelozerr** [comment]
> Sure. Will try to do it today.

I tell me if EclipsePathAdapter could belong to the minimatch.java project by creating a new project minimatch.eclipse. What do you think about that?

**Comment by piotrtomiak** [comment]
> I tell me if EclipsePathAdapter could belong to the minimatch.java project by creating a new project minimatch.eclipse. What do you think about that?

I guess it would be too many plugin-ins. I think having it in tern.eclipse is completely fine.

**Comment by angelozerr** [comment]
> I guess it would be too many plugin-ins. 

Yes it's the problem 

> I think having it in tern.eclipse is completely fine.

I had this idea because a lot of Eclipse plugins could need a support for build a scope from pattern. With minimatch.eclipse we could provide a support for that (eg: provide too IResourceVistor, abstract preferences classes, etc)

**Comment by piotrtomiak** [comment]
> It opens completion with Eclipse and debugger plays his goal. I have written something about debugging with nodeclipse at https://github.com/angelozerr/tern.java/wiki/Debugging-tern.js-with-Nodeclipse.

The debugging setup is quite similar to that from nodeclipse, except for that you don't have to rename the bin/tern file. The debugger itself is based on JSDT debug core and Chromium SDK, both heavily improved, so experience it much smoother and source mapping is seamless.

> but if Webclipse could provide a launch (ex : select your project and do Debug Tern))

Could you explain better what that launch would do?

**Comment by piotrtomiak** [comment]
> I had this idea because a lot of Eclipse plugins could need a support for build a scope from pattern. With minimatch.eclipse we could provide a support for that (eg: provide too IResourceVistor, abstract preferences classes, etc)

Right, I guess it makes sense... but maybe it will be worth doing once you are at that stage?

**Comment by angelozerr** [comment]
> Could you explain better what that launch would do?

Ok forget my last comments. I restart my idea. If you see https://github.com/angelozerr/tern.java/wiki/New-and-Noteworthy-0.4.0#user-content-nodejs-remotedirect-access

 you can set a port node to delegate the launch of tern. So today to debug with Webclise you need : 
- import ternjs plugin from workspace
- launch ternjs/node_modules/tern/bin/tern with Webclipse.
- copy the port from the Eclipse console
- save the Remote access port preference with this copied port

I think the best mean to avoid doing that is that when tern server must be started, it can delegate the server start to other component (with an extension point). 

So we could implement this extension point for Webclipse to :
- create a Webclipse launch if needed. 
- execute the launch.
- returns the port.

After that tern client will use the returned port.

We could add a new preference in a Tern/Development: "Debug with" which show a list and you will be available to select Webclipse. User must just select "Debug with Webclipse" and it will able to debug tern server.

Note that if user select that, it will propose him a dialog which tell him that if you wish to import ternjs project in her workspace.

What do you think about this idea?

**Comment by piotrtomiak** [comment]
Sounds really cool. I will talk with management on contributing something like this.

**Comment by angelozerr** [comment]
> Sounds really cool. I will talk with management on contributing something like this.

Great!

**Comment by piotrtomiak** [comment]
Ok, I thought about how to do it with the least effort ;) So the idea is that on the Node.js page we will add in the "Direct access" section a "run in debug mode (Webclipse JS Debugger)" checkbox. The checkbox will be enabled only if appropriate launch config type is available in LaunchManager, that is when Webclipse JS Debugger is actually available. That might require a bit of changes on the non UI side to enable a different way of launching, but should anyway be rather easy to achieve. Since we will use LaunchConfigurations, there should be no hard dependencies between Tern.java and Webclipse. Also, I think you or Paul will be able to integrate Nodeclipse launching as well if you like. The setting could be in that case: run in debug mode [ Webclipse JS Debugger | Nodeclipse JS Debugger ]. What do you think?

**Comment by angelozerr** [comment]
@piotrtomiak if I understand your idea, we need to add a new Table with "Debug with" label which contains the whole extension point which are able to debug node.js (Webclipse, Nodeclipse, etc). If it that, I love this idea, but we need too do teh same thing for project properties. Today this Node.js preferences is global and cannot be configured with project properties.

**Pull request merged**
